version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: employee
    ports:
      - 5432:5432
  redis:
    image: "redis:7.2-alpine"
    ports:
      - 6379:6379
    volumes:
    - ./tmp/redis_data:/var/lib/redis/data
